apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hello-world
  template:
    metadata:
      labels:
        app: flask-hello-world
    spec:
      containers:
      - name: flask-hello-world
        image: ulopeznovoa/as-lab8-test-2025
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
